[package]
name = "voxt-core-wasm"
version.workspace = true
authors.workspace = true
repository.workspace = true
documentation.workspace = true
description.workspace = true
readme.workspace = true
license.workspace = true
keywords.workspace = true
edition.workspace = true
publish.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow = { version = "1.0.104" }
console_error_panic_hook = { version = "0.1.7" }
image = { version = "0.25.10", default-features = false, features = ["png"] }
tracing = { version = "0.1.44" }
tracing-wasm = { version = "0.2.1" }
wasm-bindgen = { version = "0.2.127" }
wasm-bindgen-futures = { version = "0.4.77" }
web-sys = { version = "0.3.104", features = [
    "console",
    "Document",
    "Element",
    "HtmlCanvasElement",
    "Window",
] }
wgpu = { version = "30.0.1", features = ["webgl"] }