[package]
name = "voxt-core-native"
version.workspace = true
authors.workspace = true
repository.workspace = true
documentation.workspace = true
description.workspace = true
readme.workspace = true
license.workspace = true
keywords.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
anyhow = { version = "1.0.104" }
image = { version = "0.25.10", default-features = false, features = ["png"] }
pollster = { version = "1.0.1" }
tracing = { version = "0.1.44" }
tracing-appender = { version = "0.2.5" }
tracing-subscriber = { version = "0.3.23", features = ["env-filter", "json"] }
wgpu = { version = "30.0.1" }
winit = { version = "0.30.13" }